name = "attendancetracker"
type = "webpack"
account_id = "0d13146e53ce108313d59c78906cd900"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
site = {bucket = "./build",entry-point = "workers-site"}
compatibility_date = "2022-01-07"

[env.production]
workers_dev = false
zone_id = 'e6bf1f06148cb143e391370e9edf3aef'
route = 'https://attendancetracker.ulysseskee.software/*'